### ISSUE TITLE
Redirection to /login after authorization

### ISSUE THREAD

**Issue by Matsura33** [jcarloscid/oauthsso#2] opened 2024-07-03 14:24 UTC
Hi,
After installation and configuration, when I click the login button, I'm redirected to my SSO, I log myself with login / password and I authorize the access, after that, i'm redirected to the shopdomain.com/?auth=sso page with the authorization code and directly redirected to /login without error message. (But i'm not logged)

https://github.com/jcarloscid/oauthsso/assets/35568351/ea0fbe6f-4692-4468-a226-146eba3af444

**Comment by jcarloscid** [comment] 2024-08-05 17:35
Hi Matsura,

I am unable to reproduce the issue with just the information provided. The workflow you describe is the standard SSO flow and works in almost all installations, so in your case there is something different that make it fail.

Is it possible to have access to a testing environment where I can reproduce the issue?

I will need:
- Superadmin access to the backoffice
- Write access to the plugin's source code folder (SSH or FTP)
- Read access to server logs (SSH or FTP)
- And potentially access to the database (MySQLAdmin/Direct/SSH tunnel) [I'm not sure I would really need to use this, but eventually I might need it. Up to you to provide it now or may be later on].

For the moment I think I can manage without having access to the identity server.

Please provide credentials directly to my mailbox (carlos@fishandbits.es). Do not post here any confidential information.

KR 
Carlos

**Comment by jcarloscid** [comment] 2024-09-10 02:19
Closing issue as unable to reproduce (no information enough to do so).

**Closed as not planned** 2024-09-10 02:21 UTC
